server:
  port: 8090

spring:
  datasource:
    url: jdbc:hsqldb:hsql://localhost:9001/todos
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    show-sql: false
    hibernate.ddl-auto: create-drop